/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projekte: Projekte;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projekte: ProjekteSelect<false> | ProjekteSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Deine Projekte – anlegen, bearbeiten, sortieren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekte".
 */
export interface Projekte {
  id: number;
  titel: string;
  /**
   * Hex-Farbe, die der Titel auf der Projektseite per Klick annimmt (kleines Detail, z. B. Xepter). Leer = nicht klickbar.
   */
  titelKlickFarbe?: string | null;
  /**
   * Art des Projekts – erscheint als erste Spalte der Metazeile. z. B. „Kundenauftrag“ oder „Konzeptarbeit“.
   */
  kontext?: string | null;
  /**
   * Nur ausfüllen, wenn der Auftraggeber NICHT schon im Titel steht. Leer = die Spalte erscheint gar nicht.
   */
  kunde?: string | null;
  /**
   * 1–2 Sätze für Übersicht & Vorschau.
   */
  kurzbeschreibung: string;
  /**
   * z. B. Corporate Design, Logo, Web. Enter zum Hinzufügen.
   */
  disziplin: string[];
  /**
   * Pflicht bei „live“. Bei Platzhaltern optional.
   */
  cover?: (number | null) | Media;
  /**
   * CSS object-position, z. B. „center 30%“. Leer = center.
   */
  coverFokus?: string | null;
  /**
   * Entweder leer lassen (klassischer großer Hero) ODER genau 2 Bilder links & rechts neben dem Cover.
   */
  heroSeiten?:
    | {
        bild: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Bewegtbild oben auf der Projektseite. Leer lassen = Streifen bleibt rein aus Bildern. Läuft stumm in Endlosschleife und startet erst, wenn es beim Scrollen sichtbar wird.
   */
  heroVideo?: {
    /**
     * Bereits web-optimiert hochladen – es wird nicht neu gerechnet.
     */
    video?: (number | null) | Media;
    /**
     * Wird gezeigt, solange das Video lädt – und bei „Bewegung reduzieren“ statt des Videos. Videos taugen nicht als Cover/Vorschaubild, dafür immer ein Standbild.
     */
    poster?: (number | null) | Media;
    platzierung?: ('mitte' | 'ganze-breite') | null;
  };
  /**
   * Der eine ruhige Eröffnungssatz.
   */
  einleitung?: string | null;
  aufgabe?: string | null;
  /**
   * z. B. Logo, Geschäftsausstattung, Webdesign.
   */
  leistung?: string[] | null;
  /**
   * Wenn aktiv, wird auf der Projektseite keine Farbpalette gezeigt (wie bei ZEN).
   */
  paletteVerbergen?: boolean | null;
  /**
   * Leer = wird automatisch aus der Farbwelt abgeleitet. Eigene Hex-Werte überschreiben das.
   */
  farbpalette?: string[] | null;
  /**
   * Bausteine der Projektseite – in beliebiger Reihenfolge.
   */
  abschnitte?:
    | (
        | {
            bild: number | Media;
            bildunterschrift?: string | null;
            hoch?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'voll';
          }
        | {
            bild: number | Media;
            bildunterschrift?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'breit';
          }
        | {
            bilder: {
              bild: number | Media;
              id?: string | null;
            }[];
            bildunterschrift?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'duo';
          }
        | {
            ueberschrift?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            zitat: string;
            quelle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'zitat';
          }
      )[]
    | null;
  /**
   * Adresse der Projektseite (/projekte/<kürzel>). Wird aus dem Titel erzeugt, falls leer.
   */
  slug?: string | null;
  jahr: string;
  /**
   * Kleinere Zahl = weiter vorn auf der Startseite.
   */
  reihenfolge?: number | null;
  status: 'live' | 'in-arbeit';
  ausgezeichnet?: boolean | null;
  /**
   * Verwandelt einen Platzhalter in eine anklickbare Einladung (z. B. „Erstgespräch vereinbaren“ → /kontakt).
   */
  aktion?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Die Farben DIESER Projektwelt (Hex-Werte).
   */
  welt: {
    papier: string;
    tinte: string;
    akzent: string;
    sekundaer?: string | null;
    linie?: string | null;
    stimmung: 'hell' | 'dunkel';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle Bilder und Videos zum Wiederverwenden in Projekten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Bildbeschreibung. Hilft Suchmaschinen und Screenreadern.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    breit?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gross?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero2x?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projekte';
        value: number | Projekte;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekte_select".
 */
export interface ProjekteSelect<T extends boolean = true> {
  titel?: T;
  titelKlickFarbe?: T;
  kontext?: T;
  kunde?: T;
  kurzbeschreibung?: T;
  disziplin?: T;
  cover?: T;
  coverFokus?: T;
  heroSeiten?:
    | T
    | {
        bild?: T;
        id?: T;
      };
  heroVideo?:
    | T
    | {
        video?: T;
        poster?: T;
        platzierung?: T;
      };
  einleitung?: T;
  aufgabe?: T;
  leistung?: T;
  paletteVerbergen?: T;
  farbpalette?: T;
  abschnitte?:
    | T
    | {
        voll?:
          | T
          | {
              bild?: T;
              bildunterschrift?: T;
              hoch?: T;
              id?: T;
              blockName?: T;
            };
        breit?:
          | T
          | {
              bild?: T;
              bildunterschrift?: T;
              id?: T;
              blockName?: T;
            };
        duo?:
          | T
          | {
              bilder?:
                | T
                | {
                    bild?: T;
                    id?: T;
                  };
              bildunterschrift?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              ueberschrift?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        zitat?:
          | T
          | {
              zitat?: T;
              quelle?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  jahr?: T;
  reihenfolge?: T;
  status?: T;
  ausgezeichnet?: T;
  aktion?:
    | T
    | {
        label?: T;
        href?: T;
      };
  welt?:
    | T
    | {
        papier?: T;
        tinte?: T;
        akzent?: T;
        sekundaer?: T;
        linie?: T;
        stimmung?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        breit?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gross?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero2x?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}